### PR TITLE
Updates and Improvements

### PR DESCRIPTION
**Pull request by skellet0r**
The current LlamaPay v1 contracts are golden. This is merely a series of improvements and iterations on the original design.

Most notably things being changed are:

- Using CREATE2 for deterministic deployment of LlamaPay instances: This has the benefit that duplicate contracts won't be made such as multiple USDC or DAI LlamaPay contracts. This is because we use the _token parameter as the salt.
- Using a static array instead of a mapping for the array of already deployed instances, this is a minor improvement but saves slightly on deployment costs since there is no need to do a hash to find the slot (storage slot = 3 + indexPosition)
- Remove the ownable OZ import (bloatware) - substituted for a commit/apply scheme (but can be changed to an inline transferOwnership function if preferred)

Things Planned todo:
- Use same method as EIP-1820 to make permissionless deployment possible [Nick's method](https://weka.medium.com/how-to-send-ether-to-11-440-people-187e332566b7)
  - Aids with multichain deployments on EVM chains
  - No worrying about maintaining a private key for future deployments
- Double/Triple check logic in the LlamaPay contracts
- Would be nice to add `balanceOf` or `vestedOf` methods so that one can see their entire vested balance across all streams

Note: I use eth-brownie and python for development, but prior to taking this PR out of draft status I'll be removing any python artifacts and reverting the repo to it's fully JS status :0

### CODE REVIEW

**Comment by 0xngmi** [comment]
> use same method as EIP-1820

I was looking into it and was thinking of using [this hardhat plugin](https://github.com/wighawag/hardhat-deploy#4-deterministicdeployment-ability-to-specify-a-deployment-factory). It looks like it uses a factory (also deployed with the same mechanism mentioned in the post you linked) where you can just use create2 to deploy deterministically. I mostly like it because it already comes pre-packaged so i won't need to spend time figuring messy details with signatures.

> I use eth-brownie and python for development, but prior to taking this PR out of draft status I'll be removing any python artifacts and reverting the repo to it's fully JS status :0

imo np to just leave them, they don't affect anything and if they help then that's good

--- 

btw thanks for taking the time to look over the contracts! really appreciate it

**Comment by 0xngmi** [comment]
> Would be nice to add balanceOf or vestedOf methods so that one can see their entire vested balance across all streams

no idea how to implement this without increasing gas a substantial amount, since atm there's nothing on the contract that tracks all streams to a party

**Comment by skellet0r** [comment]
> I was looking into it and was thinking of using [this hardhat plugin](https://github.com/wighawag/hardhat-deploy#4-deterministicdeployment-ability-to-specify-a-deployment-factory). It looks like it uses a factory (also deployed with the same mechanism mentioned in the post you linked) where you can just use create2 to deploy deterministically. I mostly like it because it already comes pre-packaged so i won't need to spend time figuring messy details with signatures.

Ohhh shoot hardhat kinda cool for having plugins, can't wait for ape-framework

> no idea how to implement this without increasing gas a substantial amount, since atm there's nothing on the contract that tracks all streams to a party

yeah, I've been racking my brain at that too, the added complexity doesn't translate well :/

**Comment by 0xngmi** [comment]
btw i've merged it and applied the changes necessary to have factory be deployed at a deterministic address

**Pull request merged**
